### ISSUE TITLE
Camera Disparity

### ISSUE THREAD

**Issue by tensarflow** [ETH3D/dataset-pipeline#7]
Hey there!

I would like to test my 3D vision algorithm on your dataset [here](https://www.eth3d.net/datasets#high-res-multi-view), specifically the `delivery_area_rig_undistorted` dataset . Unfortunately I can't find any information about what stereo camera you use or what the disparity between these lenses are.
Since I couldn't find any place else to ask the question, I put it here. Sorry if it's the wrong place.
Thanks in advance!

**Comment by puzzlepaint** [comment]
We used a custom-built camera rig to record these datasets. The camera information is provided in the files cameras.txt and images.txt in the dataset archive. For a description of the format, please see: https://www.eth3d.net/documentation
